// <auto-generated />
using System;
using BlazorApp1.Server.Data_Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221022060829_dbTest5")]
    partial class dbTest5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Company", b =>
                {
                    b.Property<string>("IdCompany")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<string>("Alamat")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Departemen")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaxPhone1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaxPhone2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDirektur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKaryawan_Direktur")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("IdKota")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdLogHeader")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdValidator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdVendor_KPP")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Inisial")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("IsDVisible")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Keterangan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("KodePos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KotakPos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NPWP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nama")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PKLink1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PKLink2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefix")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Slogan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<bool?>("StatusPKP")
                        .HasColumnType("bit");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tag")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("WaktuUpdate")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Website1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Website2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdCompany");

                    b.HasIndex("IdCreator");

                    b.HasIndex("IdDirektur");

                    b.HasIndex("IdOperator");

                    b.HasIndex("IdValidator");

                    b.ToTable("T0Company");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0DivisiPerusahaan", b =>
                {
                    b.Property<Guid>("IdDivisiPerusahaan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Divisi")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLogHeader")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdValidator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDVisible")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Keterangan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tag")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("WaktuUpdate")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("IdDivisiPerusahaan");

                    b.ToTable("T0DivisiPerusahaan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Form", b =>
                {
                    b.Property<long>("IdForm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdForm"), 1L, 1);

                    b.Property<bool>("CanBatal")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBatasDataBaru")
                        .HasColumnType("bit");

                    b.Property<bool>("CanBatasLihatData")
                        .HasColumnType("bit");

                    b.Property<string>("CanCetak")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("CanDataBaru")
                        .HasColumnType("bit");

                    b.Property<bool>("CanHapus")
                        .HasColumnType("bit");

                    b.Property<bool>("CanInspeksi")
                        .HasColumnType("bit");

                    b.Property<bool>("CanLihatData")
                        .HasColumnType("bit");

                    b.Property<bool>("CanLihatRekamanAktivitas")
                        .HasColumnType("bit");

                    b.Property<bool>("CanSupervisi")
                        .HasColumnType("bit");

                    b.Property<bool>("CanUbahData")
                        .HasColumnType("bit");

                    b.Property<bool>("CanValidasi")
                        .HasColumnType("bit");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLogHeader")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdParent")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdValidator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Inisial")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Kategori")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Kode")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("NamaPK")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NamaTabel")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setting1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setting2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setting21")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Setting22")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Setting23")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Setting24")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Setting25")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Setting26")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Setting3")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setting31")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting32")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting33")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting34")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting35")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting36")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting4")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setting5")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Setting6")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tag")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("WaktuUpdate")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("IdForm");

                    b.HasIndex("IdCreator");

                    b.HasIndex("IdOperator");

                    b.HasIndex("IdValidator");

                    b.ToTable("T0Form");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Jabatan", b =>
                {
                    b.Property<Guid>("IdJabatan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKategoriJadwalKerjaKaryawan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLogHeader")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdValidator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDVisible")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Jabatan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Keterangan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Kode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PKLink1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PKLink2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tag")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("WaktuUpdate")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("IdJabatan");

                    b.ToTable("T0Jabatan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T1Karyawan", b =>
                {
                    b.Property<Guid>("IdKaryawan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("AlamatAsal")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AlamatKerabat")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AlamatTinggal")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("BPJS")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CardIdNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CardIdPin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DokumenJaminan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("FingerPrint0")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint1")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint2")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint3")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint4")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint5")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint6")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint7")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint8")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("FingerPrint9")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HubunganKerabat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDivisiPerusahaan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(2);

                    b.Property<Guid?>("IdJabatan")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<long>("IdKecamatanAsal")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKecamatanTinggal")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKelurahanAsal")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKelurahanTinggal")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKotaAsal")
                        .HasColumnType("bigint");

                    b.Property<long>("IdKotaTinggal")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IdLogHeader")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdValidator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDVisible")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRVisible")
                        .HasColumnType("bit");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Keterangan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("KodePosAsal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KodePosTinggal")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KomunikasiLain")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("NIK")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NPWP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NamaKerabat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NamaLengkap")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NamaPanggilan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomorIdentitas1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomorIdentitas2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PKLink1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PKLink2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("PasswordHint")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Rekening")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Seluler1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Seluler2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("StatusLogin")
                        .HasColumnType("bit");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tag")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("TanggalBerhenti")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("date");

                    b.Property<DateTime>("TanggalRekrut")
                        .HasColumnType("date");

                    b.Property<string>("Telepon")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TeleponKerabat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TempatLahir")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("UserPassword")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("WaktuUpdate")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("IdKaryawan");

                    b.HasIndex("IdDivisiPerusahaan");

                    b.HasIndex("IdJabatan");

                    b.ToTable("T1Karyawan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T6OrderPenjualan", b =>
                {
                    b.Property<Guid>("IdOrderPenjualan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlamatCustomer_KirimBarang_Alamat")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AlamatCustomer_KirimBarang_KodePos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_KirimBarang_Koordinat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AlamatCustomer_KirimBarang_Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_KirimBarang_NamaAlamat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AlamatCustomer_KirimDokumen_Alamat")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AlamatCustomer_KirimDokumen_KodePos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_KirimDokumen_Koordinat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AlamatCustomer_KirimDokumen_Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_KirimDokumen_NamaAlamat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AlamatCustomer_Legal_Alamat")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AlamatCustomer_Legal_KTP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_Legal_KodePos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_Legal_Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_Legal_NPWP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AlamatCustomer_Legal_NamaAlamat")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Application_ApplicationName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Attn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Batal")
                        .HasColumnType("bit");

                    b.Property<string>("Catatan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("CetakFaktur")
                        .HasColumnType("int");

                    b.Property<string>("Customer_Alamat")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Customer_Customer")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Customer_Email1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Customer_FaxPhone1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Customer_Inisial")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Customer_KodePos")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Customer_Kota")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Customer_NPWP")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Customer_Nama")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Customer_Phone1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Customer_StatusPKP")
                        .HasColumnType("bit");

                    b.Property<string>("DeliveryBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DiskonDetil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("DiskonNominal")
                        .HasColumnType("money");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("money");

                    b.Property<Guid?>("IdAlamatCustomer_KirimBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdAlamatCustomer_KirimDokumen")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdAlamatCustomer_Legal")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdCompany")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<Guid?>("IdCompany_Pengirim")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdInspector")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdJenisCustomer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdJenisTransaksi")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKaryawan_Salesman")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdLogHeader")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdPenyeliaCustomer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSupervisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdTransaksi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("IdValidator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JenisCustomer_Jenis")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("JenisTransaksi_Jenis")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Karyawan_Creator")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Karyawan_Inspector")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Karyawan_Operator")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Karyawan_Salesman_NamaPanggilan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Karyawan_Supervisor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Karyawan_Validator")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KodePOCustomer")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NoTransaksi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PKLink1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PKLink2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PPNDetil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("PPNNominal")
                        .HasColumnType("money");

                    b.Property<string>("Pembayaran_Keterangan")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("Pembayaran_StatusTerbayar")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Pembayaran_Total")
                        .HasColumnType("money");

                    b.Property<string>("Pembayaran_Via")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PenyeliaCustomer_Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PenyeliaCustomer_Jabatan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PenyeliaCustomer_JenisKelamin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PenyeliaCustomer_Nama")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PenyeliaCustomer_Phone1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PenyeliaCustomer_Phone2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PenyeliaCustomer_Prefix")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Periode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Preview")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Simpan")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("T1KaryawanIdKaryawan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("WaktuInsert")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("WaktuKirim")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("WaktuProses")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("WaktuUpdate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IdOrderPenjualan");

                    b.HasIndex("T1KaryawanIdKaryawan");

                    b.ToTable("T6OrderPenjualan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T7OrderPenjualan", b =>
                {
                    b.Property<Guid>("IdDetilOrderPenjualan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barang_Barang")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Barang_Kode1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Barang_Kode2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Barang_Merk")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Barang_Ukuran")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Barang_Umur")
                        .HasColumnType("int");

                    b.Property<string>("Barang_Warna")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Berat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CatatanOrder")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CatatanPersetujuan")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTimeOffset?>("DiskonBarang_WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DiskonDetil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("DiskonNominal")
                        .HasColumnType("money");

                    b.Property<string>("DivisiBarang_Divisi")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("Harga")
                        .HasColumnType("money");

                    b.Property<DateTimeOffset?>("HargaBarang_WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("IdBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDetilKontrakPenjualan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDiskonBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDivisiBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHargaBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKategoriBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKurs")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdOrderPenjualan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSatuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSubDivisiBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSubKategoriBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JenisBarang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("JenisHargaDiskon")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Jumlah")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long?>("JumlahRealisasi")
                        .HasColumnType("bigint");

                    b.Property<string>("KategoriBarang_Kategori")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("Kuantum_DiskonBarang_WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Kuantum_DiskonDetil")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Kuantum_DiskonNominal")
                        .HasColumnType("money");

                    b.Property<decimal?>("Kuantum_Harga")
                        .HasColumnType("money");

                    b.Property<DateTimeOffset?>("Kuantum_HargaBarang_WaktuInsert")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("Kuantum_IdDiskonBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Kuantum_IdHargaBarang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Kuantum_IdSatuan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Kuantum_JenisHargaDiskon")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Kuantum_Jumlah")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Kuantum_Kuantum")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("Kuantum_Total")
                        .HasColumnType("money");

                    b.Property<string>("Kurs_Kurs")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Kurs_Simbol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("NilaiKurs")
                        .HasColumnType("money");

                    b.Property<bool?>("Pemutihan")
                        .HasColumnType("bit");

                    b.Property<bool?>("Persetujuan")
                        .HasColumnType("bit");

                    b.Property<Guid?>("Referensi_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Referensi_IdTransaksi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTimeOffset?>("Referensi_WaktuProses")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte?>("Satuan_SKUGrup")
                        .HasColumnType("tinyint");

                    b.Property<string>("Satuan_SKUKode1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Satuan_SKUKode2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("Satuan_SKULevel")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Satuan_SKURasio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Satuan_Satuan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("Satuan_UseSerialNumber")
                        .HasColumnType("bit");

                    b.Property<bool?>("StatusTerealisasi")
                        .HasColumnType("bit");

                    b.Property<string>("SubDivisiBarang_SubDivisi")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SubKategoriBarang_SubKategori")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("money");

                    b.Property<DateTimeOffset?>("WaktuPersetujuan")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("IdDetilOrderPenjualan");

                    b.HasIndex("IdOperator");

                    b.HasIndex("IdOrderPenjualan");

                    b.ToTable("T7OrderPenjualan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T9Privileges", b =>
                {
                    b.Property<Guid>("IdKaryawan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("IdForm")
                        .HasColumnType("bigint");

                    b.Property<string>("IdCompany")
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<string>("BatasDataBaru")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BatasLihatData")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cetak")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<byte?>("DataBaru")
                        .HasColumnType("tinyint");

                    b.Property<string>("Grup")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("IdOperator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Inspeksi")
                        .HasColumnType("bit");

                    b.Property<bool?>("LihatRekamanAktivitas")
                        .HasColumnType("bit");

                    b.Property<short?>("PoinApprove")
                        .HasColumnType("smallint");

                    b.Property<short?>("PoinDecline")
                        .HasColumnType("smallint");

                    b.Property<bool?>("Setting1")
                        .HasColumnType("bit");

                    b.Property<bool?>("Setting2")
                        .HasColumnType("bit");

                    b.Property<byte?>("Setting21")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Setting22")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Setting23")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Setting24")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Setting25")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Setting26")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("Setting3")
                        .HasColumnType("bit");

                    b.Property<string>("Setting31")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting32")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting33")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting34")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting35")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Setting36")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool?>("Setting4")
                        .HasColumnType("bit");

                    b.Property<bool?>("Setting5")
                        .HasColumnType("bit");

                    b.Property<bool?>("Setting6")
                        .HasColumnType("bit");

                    b.Property<bool?>("Supervisi")
                        .HasColumnType("bit");

                    b.Property<string>("Synchronise")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte?>("Urutan")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("ValidasiPassword")
                        .HasColumnType("bit");

                    b.HasKey("IdKaryawan", "IdForm", "IdCompany");

                    b.HasIndex("IdCompany");

                    b.HasIndex("IdForm");

                    b.ToTable("T9Privileges");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Company", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Creator")
                        .WithMany()
                        .HasForeignKey("IdCreator");

                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Direktur")
                        .WithMany()
                        .HasForeignKey("IdDirektur");

                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Operator")
                        .WithMany()
                        .HasForeignKey("IdOperator");

                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Validator")
                        .WithMany()
                        .HasForeignKey("IdValidator");

                    b.Navigation("T1Karyawan_Creator");

                    b.Navigation("T1Karyawan_Direktur");

                    b.Navigation("T1Karyawan_Operator");

                    b.Navigation("T1Karyawan_Validator");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Form", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Creator")
                        .WithMany()
                        .HasForeignKey("IdCreator");

                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Operator")
                        .WithMany()
                        .HasForeignKey("IdOperator");

                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Validator")
                        .WithMany()
                        .HasForeignKey("IdValidator");

                    b.Navigation("T1Karyawan_Creator");

                    b.Navigation("T1Karyawan_Operator");

                    b.Navigation("T1Karyawan_Validator");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T1Karyawan", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Etms.T0DivisiPerusahaan", "T0DivisiPerusahaan")
                        .WithMany()
                        .HasForeignKey("IdDivisiPerusahaan");

                    b.HasOne("BlazorApp1.Shared.Etms.T0Jabatan", "T0Jabatan")
                        .WithMany("ListKaryawan")
                        .HasForeignKey("IdJabatan");

                    b.Navigation("T0DivisiPerusahaan");

                    b.Navigation("T0Jabatan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T6OrderPenjualan", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", null)
                        .WithMany("ListT6OrderPenjualan")
                        .HasForeignKey("T1KaryawanIdKaryawan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T7OrderPenjualan", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan_Operator")
                        .WithMany()
                        .HasForeignKey("IdOperator");

                    b.HasOne("BlazorApp1.Shared.Etms.T6OrderPenjualan", "T6OrderPenjualan")
                        .WithMany("ListT7OrderPenjualan")
                        .HasForeignKey("IdOrderPenjualan");

                    b.Navigation("T1Karyawan_Operator");

                    b.Navigation("T6OrderPenjualan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T9Privileges", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Etms.T0Company", "T0Company")
                        .WithMany("ListT9Privileges")
                        .HasForeignKey("IdCompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Shared.Etms.T0Form", "T0Form")
                        .WithMany("ListT9Privileges")
                        .HasForeignKey("IdForm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp1.Shared.Etms.T1Karyawan", "T1Karyawan")
                        .WithMany("ListT9Privileges")
                        .HasForeignKey("IdKaryawan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("T0Company");

                    b.Navigation("T0Form");

                    b.Navigation("T1Karyawan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Company", b =>
                {
                    b.Navigation("ListT9Privileges");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Form", b =>
                {
                    b.Navigation("ListT9Privileges");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T0Jabatan", b =>
                {
                    b.Navigation("ListKaryawan");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T1Karyawan", b =>
                {
                    b.Navigation("ListT6OrderPenjualan");

                    b.Navigation("ListT9Privileges");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Etms.T6OrderPenjualan", b =>
                {
                    b.Navigation("ListT7OrderPenjualan");
                });
#pragma warning restore 612, 618
        }
    }
}
